/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author Marvin
 */
public class Dialogo_log extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final boolean RET_CANCEL = false;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final boolean RET_OK = true;

    public enum Tam {

        M3, M5, M7
    };
    Tam matrix_select;

    /**
     * Creates new form Dialogo_log
     */
    public Dialogo_log(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public boolean getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radio_3x3 = new javax.swing.JRadioButton();
        radio_5x5 = new javax.swing.JRadioButton();
        radio_7x7 = new javax.swing.JRadioButton();
        m00 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m20 = new javax.swing.JTextField();
        m21 = new javax.swing.JTextField();
        m11 = new javax.swing.JTextField();
        m01 = new javax.swing.JTextField();
        m02 = new javax.swing.JTextField();
        m12 = new javax.swing.JTextField();
        m22 = new javax.swing.JTextField();
        radio_b = new javax.swing.JRadioButton();
        radio_a = new javax.swing.JRadioButton();
        radio_c = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radio_d = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Laplaciano del Gaussiano");

        buttonGroup1.add(radio_3x3);
        radio_3x3.setText("Usar matriz de 3 x 3");
        radio_3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_3x3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_5x5);
        radio_5x5.setText("Usar matriz de 5 x 5");
        radio_5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_5x5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_7x7);
        radio_7x7.setText("Usar matriz de 7 x 7");
        radio_7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_7x7ActionPerformed(evt);
            }
        });

        m00.setEditable(false);
        m00.setText("0");
        m00.setMaximumSize(new java.awt.Dimension(6, 20));

        m10.setEditable(false);
        m10.setText("1");
        m10.setMaximumSize(new java.awt.Dimension(6, 20));

        m20.setEditable(false);
        m20.setText("0");
        m20.setMaximumSize(new java.awt.Dimension(6, 20));

        m21.setEditable(false);
        m21.setText("0");
        m21.setMaximumSize(new java.awt.Dimension(6, 20));

        m11.setEditable(false);
        m11.setText("-4");
        m11.setMaximumSize(new java.awt.Dimension(6, 20));

        m01.setEditable(false);
        m01.setText("1");
        m01.setMaximumSize(new java.awt.Dimension(6, 20));

        m02.setEditable(false);
        m02.setText("0");
        m02.setMaximumSize(new java.awt.Dimension(6, 20));

        m12.setEditable(false);
        m12.setText("1");
        m12.setMaximumSize(new java.awt.Dimension(6, 20));

        m22.setEditable(false);
        m22.setText("0");
        m22.setMaximumSize(new java.awt.Dimension(6, 20));

        buttonGroup2.add(radio_b);
        radio_b.setText("Tipo B");
        radio_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_bActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_a);
        radio_a.setSelected(true);
        radio_a.setText("Tipo A");
        radio_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_aActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_c);
        radio_c.setText("Tipo C");
        radio_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Laplaciano");

        buttonGroup2.add(radio_d);
        radio_d.setText("Tipo D");
        radio_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Filtro Gaussiano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radio_3x3)
                                            .addComponent(radio_7x7)
                                            .addComponent(radio_5x5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radio_c)
                                            .addComponent(radio_b)
                                            .addComponent(radio_a)
                                            .addComponent(radio_d)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_3x3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_5x5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_7x7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(okButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(radio_a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_b)
                        .addGap(3, 3, 3)
                        .addComponent(radio_c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_d)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void radio_5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_5x5ActionPerformed
        matrix_select = Tam.M5;
    }//GEN-LAST:event_radio_5x5ActionPerformed

    private void radio_3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_3x3ActionPerformed
        matrix_select = Tam.M3;
    }//GEN-LAST:event_radio_3x3ActionPerformed

    private void radio_7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_7x7ActionPerformed
        matrix_select = Tam.M7;
    }//GEN-LAST:event_radio_7x7ActionPerformed

    private void radio_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_bActionPerformed
        m00.setText("0");
        m10.setText("-1");
        m20.setText("0");
        m01.setText("-1");
        m11.setText("4");
        m21.setText("-1");
        m02.setText("0");
        m12.setText("-1");
        m22.setText("0");
    }//GEN-LAST:event_radio_bActionPerformed

    private void radio_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_aActionPerformed
        m00.setText("0");
        m10.setText("1");
        m20.setText("0");
        m01.setText("1");
        m11.setText("-4");
        m21.setText("1");
        m02.setText("0");
        m12.setText("1");
        m22.setText("0");
    }//GEN-LAST:event_radio_aActionPerformed

    private void radio_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cActionPerformed
        m00.setText("1");
        m10.setText("1");
        m20.setText("1");
        m01.setText("1");
        m11.setText("-8");
        m21.setText("1");
        m02.setText("1");
        m12.setText("1");
        m22.setText("1");
    }//GEN-LAST:event_radio_cActionPerformed

    private void radio_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dActionPerformed
        m00.setText("-1");
        m10.setText("-1");
        m20.setText("-1");
        m01.setText("-1");
        m11.setText("8");
        m21.setText("-1");
        m02.setText("-1");
        m12.setText("-1");
        m22.setText("-1");
    }//GEN-LAST:event_radio_dActionPerformed

    private void doClose(boolean retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public double[][] getLaplaciano() {
        double p1 = Double.parseDouble(m00.getText());
        double p2 = Double.parseDouble(m10.getText());
        double p3 = Double.parseDouble(m20.getText());
        double p4 = Double.parseDouble(m01.getText());
        double p5 = Double.parseDouble(m11.getText());
        double p6 = Double.parseDouble(m21.getText());
        double p7 = Double.parseDouble(m02.getText());
        double p8 = Double.parseDouble(m12.getText());
        double p9 = Double.parseDouble(m22.getText());
        double[][] m = {{p1,p2,p3}, {p4,p5,p6}, {p7,p8,p9}};
        return m;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialogo_log dialog = new Dialogo_log(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField m00;
    private javax.swing.JTextField m01;
    private javax.swing.JTextField m02;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m11;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField m20;
    private javax.swing.JTextField m21;
    private javax.swing.JTextField m22;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton radio_3x3;
    private javax.swing.JRadioButton radio_5x5;
    private javax.swing.JRadioButton radio_7x7;
    private javax.swing.JRadioButton radio_a;
    private javax.swing.JRadioButton radio_b;
    private javax.swing.JRadioButton radio_c;
    private javax.swing.JRadioButton radio_d;
    // End of variables declaration//GEN-END:variables
    private boolean returnStatus = RET_CANCEL;
}
